application: gae-starter
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: img/favicon.ico
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /img
  static_dir: static/img
- url: .*
  script: src.main.app

# builtins:
# - appstats: on

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "latest"
